theme: jekyll-theme-cayman
domain: edwardcole.github.io/ticket-dollar-index       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://edwardcole.github.io/ticket-dollar-index  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder
